"""add_social_urls_to_parish

Revision ID: d365940dc964
Revises: 74ad24c0f7d8
Create Date: 2026-04-21 19:01:13.961697

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd365940dc964'
down_revision: Union[str, None] = '74ad24c0f7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parish', sa.Column('facebook_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('parish', sa.Column('instagram_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('parish', sa.Column('youtube_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('parish', sa.Column('whatsapp', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parish', 'whatsapp')
    op.drop_column('parish', 'youtube_url')
    op.drop_column('parish', 'instagram_url')
    op.drop_column('parish', 'facebook_url')
    # ### end Alembic commands ###
