"""multi_tenancy_parish

Revision ID: f69a3b1b526e
Revises: 89bcec7af283
Create Date: 2026-04-21 14:55:27.877350

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69a3b1b526e'
down_revision: Union[str, None] = '89bcec7af283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parish_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_category_parish_id'), 'category', ['parish_id'], unique=False)
    op.create_foreign_key(None, 'category', 'parish', ['parish_id'], ['id'])
    op.add_column('celebration', sa.Column('parish_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_celebration_parish_id'), 'celebration', ['parish_id'], unique=False)
    op.create_foreign_key(None, 'celebration', 'parish', ['parish_id'], ['id'])
    op.add_column('role', sa.Column('parish_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_role_parish_id'), 'role', ['parish_id'], unique=False)
    op.create_foreign_key(None, 'role', 'parish', ['parish_id'], ['id'])
    op.add_column('user', sa.Column('parish_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_user_parish_id'), 'user', ['parish_id'], unique=False)
    op.create_foreign_key(None, 'user', 'parish', ['parish_id'], ['id'])
    op.add_column('warning', sa.Column('parish_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_warning_parish_id'), 'warning', ['parish_id'], unique=False)
    op.create_foreign_key(None, 'warning', 'parish', ['parish_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warning', type_='foreignkey')
    op.drop_index(op.f('ix_warning_parish_id'), table_name='warning')
    op.drop_column('warning', 'parish_id')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_parish_id'), table_name='user')
    op.drop_column('user', 'parish_id')
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_index(op.f('ix_role_parish_id'), table_name='role')
    op.drop_column('role', 'parish_id')
    op.drop_constraint(None, 'celebration', type_='foreignkey')
    op.drop_index(op.f('ix_celebration_parish_id'), table_name='celebration')
    op.drop_column('celebration', 'parish_id')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_index(op.f('ix_category_parish_id'), table_name='category')
    op.drop_column('category', 'parish_id')
    # ### end Alembic commands ###
